version: '1.2'

services:
  appServer:
    image: diplom:latest
    container_name: 'server'

    environment:
      spring.datasource.url: 'jdbc:postgresql://db:5432/postgres'
      spring.jpa.hibernate.ddl-auto: 'create-drop'

    ports:
      - '8080:8080'

    depends_on:
      - db

  db:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres